### ISSUE TITLE
forAll sample size incorrectly set to constant 1

### ISSUE THREAD

**Issue by cihleman3** [typelevel/scalacheck-effect#136]
`PropF.forAll { (s: String) =>` does not increase the size of the strings it is testing: it only uses strings of length 0 or 1.
(The same holds for lists and presumably for alle "size-sensitive" data, i.e., not numbers.)
The apparent reason is that the loop inside of `check` implementing the quantifier uses a constant size of 1:
`val size = minSize.toDouble + sizeStep`.

**Comment by arosien** [comment]
I think you mean that the sample size is incorrectly set to be constant (size 1!). Can you update the description? Saying "does not increase" implies the sample size increases, which is not technically correct; the sample size _bounds_ are set (incorrectly!) and do not vary.

**Comment by arosien** [comment]
Re: constant size:

```scala
val sizeStep = (maxSize - minSize) / minSuccessfulTests
...
val size = minSize.toDouble + sizeStep
```
The default parameters are:
- maxSize = 100
- minSize = 0
- minSuccessfulTests = 100
therefore size is set to 1.

**Comment by cihleman3** [comment]
Ok, is it clearer now?

**Comment by arosien** [comment]
Looking at the [impl](https://github.com/typelevel/scalacheck-effect/blob/main/core/shared/src/main/scala/org/scalacheck/effect/PropF.scala#L89) which computes this `stepSize`, it's not clear to me what it is for. Couldn't the size parameters be unmodified from their defaults, which would avoid the bug?

**Comment by mpilquist** [comment]
Wow, thanks for finding this one. I'm amazed we haven't noticed this behavior until now!
